Repository pengutronix/meta-ptx, pull requests merged in 2020-11, with the labels that each got.

#55 barebox: prevent BAREBOX_IMAGES check from failing unintentionally
  recipes-bsp/barebox/barebox.inc
Labels: bug

#57 barebox: allow using config fragments
  recipes-bsp/barebox/barebox.inc
Labels: enhancement

#56 barebox: allows building standard defconfig
  recipes-bsp/barebox/barebox.inc
Labels: enhancement

#59 genimage: inherit image-artifact-names
  classes/genimage.bbclass
Labels: gatesgarth, master

#61 distro/ptx.conf: update to gatesgarth (3.2)
  conf/distro/ptx.conf
Labels: enhancement, gatesgarth

#62 Add CI build using GitHub Actions
  .github/workflows/meta-ptx.yml
  README.md
Labels: master, testing

#63 barebox: update to 2020.11.0
  recipes-bsp/barebox/barebox_2019.05.0.bb
  recipes-bsp/barebox/barebox_2020.11.0.bb
Labels: master, version bump
