Repository pengutronix/meta-ptx, pull requests merged in 2021-08, with the labels that each got.

#90 update to honister's new override style syntax
  .github/workflows/meta-ptx.yml
  classes/bootspec.bbclass
  conf/distro/ptx.conf
  conf/layer.conf
  recipes-bsp/barebox/barebox.inc
  recipes-core/busybox/busybox_%.bbappend
  recipes-core/dt-utils/dt-utils.inc
  recipes-core/ptx-profile/ptx-profile.bb
  recipes-core/systemd/systemd-rc-once.bb
Labels: master, honister

#91 classes: genimage: fix dependency syntax in example
  classes/genimage.bbclass
Labels: documentation

#88 barebox: remove TARGETCFLAGS
  recipes-bsp/barebox/barebox.inc
Labels: master
