Repository pengutronix/meta-ptx, pull requests merged in 2021-06, with the labels that each got.

#83 genimage: update to v14
  recipes-devtools/genimage/genimage_13.bb
  recipes-devtools/genimage/genimage_14.bb
Labels: version bump

#75 confuse and genimage: Add nativesdk to BBCLASSEXTEND
  recipes-devtools/confuse/confuse_2.7.bb
  recipes-devtools/genimage/genimage.inc
Labels: enhancement

#81 genimage.bbclass: clean ${B} completely before building
  classes/genimage.bbclass
Labels: bugfix, enhancement

#85 genimage.bbclass: fix grep usage in do_configure
  classes/genimage.bbclass
Labels: bugfix

#67 Add bootspec support for external device tree's
  classes/bootspec.bbclass
Labels: enhancement

#80 genimage.bbclass: add bmaptool support
  classes/genimage.bbclass
Labels: enhancement

#84 confuse and genimage: Add nativesdk to BBCLASSEXTEND
  recipes-devtools/confuse/confuse_2.7.bb
  recipes-devtools/genimage/genimage.inc
Labels: dunfell
